language: node_js
node_js:
    - "6.1.0"

branches:
    only:
        - "master"

before_install:
    - npm i addons-linter web-ext -g
    - rm -f ./web-ext-artifacts/*.zip

script:
    - npm run build
    - addons-linter ./web-ext-artifacts/*.zip -o text
